# Greeting
greeting:
  message: hello

# Quarkus Native Resources
quarkus:
  # Mailer Configuration
  mailer:
    from: support@crypto.com
    host: smtp.hostinger.com
    username: support@crypto.com
    password: j9n9$xf4GP!+2YE
    mock: false
    port: 587

  native:
    resources:
      includes: META-INF/resources/publicKey.pem

  # Swagger UI
  swagger-ui:
    path: /documentation
    always-include: true
    theme: outline
    title: CRYPTO API
    footer: 2025 . CRYPTO
    enable: true

  # Disable Dev Services
  devservices:
    enabled: false

  # Datasource (PostgreSQL)
  datasource:
    db-kind: postgresql
    username: postgres
    password: alloma
    jdbc:
      url: jdbc:postgresql://localhost:5432/cryptodb

  # HTTP Configuration
  http:
    host: 0.0.0.0
    port: 8080

  # Kubernetes Configuration
  kubernetes:
    part-of: crypto-k8s
    image-pull-policy: never
    service-type: node-port
    node-port: 30011
    replicas: 3
    pvc-volumes:
      task-pv-storage:
        claim-name: task-pv-claim
    mounts:
      task-pv-storage:
        path: /home/dev1/crypto/jar

  # Container Image
  container-image:
    registry: ""
    group: ""
    name: crypto-k8s
    tag: 1.0

  # Liquibase Configuration
  liquibase:
    migrate-at-start: true
    change-log: db/changelog.xml
    baseline-on-migrate: true

# JVM Arguments
jvm:
  args: "--add-opens=java.base/java.lang=ALL-UNNAMED"

# JWT Verification
mp:
  jwt:
    verify:
      issuer: crypto-api
      publickey:
        location: classpath:publicKey.pem

# JWT Signing Key
smallrye:
  jwt:
    sign:
      key:
        location: classpath:privateKey.pem

# Upload Directories
upload:
  base-dir: /tmp/crypto-files
  files_dir: /files
  template: /template

# Application Crypto
crypto:
  name: CRYPTO
  paystack_secret_key: sk_test_a870c3e9bb1ceaed9c0355a94c5ac0f116c88e74
  paystack_public_key: pk_test_da8f16bc70e61520fee8cf7c8d586523503084c7
  paystack_callback_url: http://localhost:4200/payment-callback?email={customer_email}
  paystack_webhook_url: http://localhost:8080/payment/webhook/
