--liquibase formatted sql

--changeset cryptoneo:1.0.0-initial-schema dbms:postgresql
--comment: Création du schéma de base de données initial pour toutes les entités.

-- Création des tables
CREATE TABLE accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code varchar(20) NOT NULL,
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean,
    deleted_at timestamp(6) with time zone,
    email varchar(255) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    password varchar(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    person_id bigint,
    role_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE book_loans (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code varchar(20) NOT NULL,
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean,
    deleted_at timestamp(6) with time zone,
    is_active boolean DEFAULT true NOT NULL,
    updated_at timestamp(6) with time zone,
    book_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE books (
    id bigint NOT NULL,
    active boolean DEFAULT true NOT NULL,
    code varchar(20) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    deleted boolean,
    deleted_at timestamp(6) with time zone,
    description varchar(255),
    isbn varchar(255),
    "publicationYear" integer NOT NULL,
    title varchar(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    PRIMARY KEY (id)
);

CREATE TABLE cities (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code varchar(20) NOT NULL,
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean,
    deleted_at timestamp(6) with time zone,
    is_active boolean DEFAULT true NOT NULL,
    name varchar(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    PRIMARY KEY (id)
);

CREATE TABLE libraries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    address varchar(255),
    code varchar(20) NOT NULL,
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean NOT NULL,
    deleted_at timestamp(6) with time zone,
    is_active boolean DEFAULT true NOT NULL,
    updated_at timestamp(6) with time zone,
    city_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code varchar(20) NOT NULL,
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean NOT NULL,
    deleted_at timestamp(6) with time zone,
    is_active boolean DEFAULT true NOT NULL,
    name varchar(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    PRIMARY KEY (id)
);

CREATE TABLE persons (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code varchar(20),
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean DEFAULT false,
    deleted_at timestamp(6) with time zone,
    email varchar(255) NOT NULL,
    first_name varchar(255),
    last_name varchar(255),
    active boolean DEFAULT true NOT NULL,
    type varchar(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    PRIMARY KEY (id)
);

CREATE TABLE role_permissions (
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL
);

CREATE TABLE roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code varchar(20) NOT NULL,
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean NOT NULL,
    deleted_at timestamp(6) with time zone,
    is_active boolean DEFAULT true NOT NULL,
    name varchar(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    PRIMARY KEY (id)
);

